dist: trusty
notifications:
  email: false

language: rust
rust:
  - 1.18.0
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - nightly
cache:
  cargo: true
  directories:
    - front/node_modules

addons:
  postgresql: "9.5"
  apt:
    packages:
      - curl
      - libpq-dev
      - phantomjs
      - pkg-config

before_install:
  - nvm install 6
  - npm config set spin false
  - npm install -g phantomjs-prebuilt yarn ember-cli
  - phantomjs --version
install:
  - cd front/
  - yarn install
  - cd ../
  - cargo install --force diesel_cli --no-default-features --features "postgres"

before_script:
  - export RUST_LOG=debug,hyper=info,rustc=error,cargo=error
  - export GITHUB_WEBHOOK_SECRETS="none"
  - export POST_COMMENTS=false
  - export RUST_BACKTRACE=1
  - export PATH=$PATH:$HOME/.cargo/bin
  - export DATABASE_URL='postgres://localhost/dashboard'
  - diesel setup
  - diesel migration run

script:
  - diesel print-schema > ./current_schema && cmp --silent src/domain/schema.rs ./current_schema
  - cargo build --verbose
  - cargo test --verbose
  - cd front && ember build
