dist: trusty
notifications:
  email: false

language: rust
rust:
  - nightly

cache:
  cargo: true
  directories:
  - $HOME/.rustup

addons:
  postgresql: "9.5"
  apt:
    packages:
      - curl
      - libpq-dev
      - pkg-config

install:
  - rustup default nightly-2017-08-26
  - cargo install --force diesel_cli --no-default-features --features "postgres"

before_script:
  - export RUST_LOG=debug,hyper=info,rustc=error,cargo=error
  - export GITHUB_WEBHOOK_SECRETS="none"
  - export POST_COMMENTS=false
  - export RUST_BACKTRACE=1
  - export PATH=$PATH:$HOME/.cargo/bin
  - export DATABASE_URL='postgres://localhost/dashboard'
  - diesel setup
  - diesel migration run

script:
  - diesel print-schema > ./current_schema
  - ls -la src/domain/schema.rs
  - cat src/domain/schema.rs
  - cmp src/domain/schema.rs ./current_schema
  - cargo build --verbose
  - cargo test --verbose
