[package]
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
name = "rust-dashboard"
version = "0.1.0"
[dependencies]
afterparty = { version = "0.1.2", path = "vendor/afterparty" }
clap = "2.2.5"
crossbeam = "0.2.9"
dotenv = "0.8.0"
env_logger = "0.3.3"
hyper = "0.10.0"
iron = "0.5.0"
lazy_static = "0.2.0"
log = "0.3.6"
mount = "0.3.0"
r2d2 = "0.7.0"
r2d2-diesel = "0.8"
regex = "0.1"
router = "0.5.0"
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
urlencoded = "0.5.0"

[dependencies.chrono]
features = ["serde"]
version = "0.2.25"

[dependencies.diesel]
default-features = false
features = ["postgres", "chrono", "large-tables"]
version = "0.8"

[dependencies.diesel_codegen]
default-features = false
features = ["dotenv", "postgres"]
version = "0.8"

[profile]
[profile.release]
debug = false
