[package]
name = "rust-dashboard"
version = "0.1.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]

[dependencies]
chrono = {version = "0.2.21", features = ["serde"] }
clap = "2.2.5"
dotenv = "0.8.0"
dotenv_macros = "0.8.0"
env_logger = "0.3.3"
hyper = "0.8.0"
lazy_static = "0.2.0"
log = "0.3.6"
r2d2 = "0.7.0"
r2d2-diesel = "0.6.0"
serde = "0.7.0"
serde_json = "0.7.0"
serde_macros = "0.7.0"

[dependencies.diesel]
version = "0.6.1"
default-features = false
features = ["postgres", "chrono"]

[dependencies.diesel_codegen]
version = "0.6.1"
default-features = false
features = ["nightly", "postgres"]
