[T-core]
name = "Core"
ping = "rust-lang/core"
members = [
  "alexcrichton",
  "ashleygwilliams",
  "aturon",
  "carols10cents",
  "nikomatsakis",
  "nrc",
  "steveklabnik",
  "wycats",
  "aidanhs",
  "Mark-Simulacrum",
]

[T-lang]
name = "Language"
ping = "rust-lang/lang"
members = [
  "aturon",
  "cramertj",
  "eddyb",
  "nikomatsakis",
  "nrc",
  "pnkfelix",
  "withoutboats",
  "joshtriplett",
  "scottmcm",
]

[T-libs]
name = "Libraries"
ping = "rust-lang/libs"
members = [
  "alexcrichton",
  "dtolnay",
  "sfackler",
  "withoutboats",
  "Kimundi",
  "aturon",
  "SimonSapin",
]

[T-compiler]
name = "Compiler"
ping = "rust-lang/compiler"
members = [
  "cramertj",
  "eddyb",
  "estebank",
  "michaelwoerister",
  "nikomatsakis",
  "nrc",
  "petrochenkov",
  "pnkfelix",
  "Zoxc",
  "nagisa",
  "oli-obk",
]

[T-doc]
name = "Documentation"
ping = "rust-lang/docs"
members = [
  "frewsxcv",
  "GuillaumeGomez",
  "QuietMisdreavus",
  "steveklabnik",
]

[T-infra]
name = "Infrastructure"
ping = "rust-lang/infra"
members = [
  "aidanhs",
  "alexcrichton",
  "aturon",
  "carols10cents",
  "erickt",
  "kennytm",
  "Mark-Simulacrum",
  "shepmaster",
  "TimNN",
]

[T-cargo]
name = "Cargo"
ping = "rust-lang/cargo"
members = [
  "alexcrichton",
  "aturon",
  "carols10cents",
  "joshtriplett",
  "matklad",
  "withoutboats",
  "wycats",
]

[T-dev-tools]
name = "Dev tools"
ping = "rust-lang/dev-tools"
members = [
  "fitzgen",
  "japaric",
  "killercup",
  "nrc",
  "Manishearth",
  "withoutboats",
  "steveklabnik",
]

[T-dev-tools-rustdoc]
name = "Rustdoc"
ping = "rust-lang/rustdoc"
members = [
  "GuillaumeGomez",
  "QuietMisdreavus",
  "ollie27",
  "onur",
  "steveklabnik",
]

[T-IDEs]
name = "IDEs and editors"
ping = "rust-lang/IDEs"
members = [
  "alexheretic",
  "autozimu",
  "jasonwilliams",
  "LucasBullen",
  "matklad",
  "nrc",
  "vlad20012",
  "Xanewok",
]
